version: 2
jobs:
  build:
    working_directory: ~/classivo
    docker:
      - image: angular/ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: classivo-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: classivo-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run lint -- --type-check

  deploy:
    working_directory: ~/classivo
    docker:
      - image: angular/ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: classivo-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: classivo-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run build -- --prod --no-progress
      - run: npm run deploy -- --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
