version: 2
jobs:
  build:
    working_directory: ~/classivo
    docker:
      - image: angular/ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: classivo-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: classivo-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run lint

  deploy:
    working_directory: ~/classivo
    branch: master
    docker:
      - image: angular/ngcontainer
    steps:
      - checkout
      - run: npm install --production
      - run: npm run build -- --prod
      - run: npm run deploy -- --token=$FIREBASE_TOKEN --non-interactive

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
