version: 2
jobs:
  build:
    working_directory: ~/classivo
    docker:
      - image: angular/ngcontainer
    steps:
      - checkout
      - restore_cache:
          key: classivo-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: classivo-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: npm run lint
